version: '3'
services:
  postgres:
    container_name: postgres              #nome utilizado nas entradas de conexão do Zabbix
    hostname: postgres                    #nome do servidor hostname
    image: postgres:latest                #imagem oficial da sua ultima versão
    ports:
      - 5432:5432                         #porta padrao exposta
    volumes:
      - pgdata:/var/lib/postgresql/data   #criaçao de um volume no docker para persistir os dados
    restart: always
    environment:
      - POSTGRES_DB=zabbix                #nome da base de dados
      - POSTGRES_USER=zabbix              #nome do usuario do banco de dados
      - POSTGRES_PASSWORD=suasenha        #senha do usuario do banco de dados

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    hostname: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:latest
    restart: always
    ports:
      - 10051:10051
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=suasenha
    depends_on:
      - postgres

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=suasenha
      - PHP_TZ=America/Sao_Paulo
      - ZBX_DEBUGLEVEL=5
    deploy:
      replicas: 2
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.0-latest
    container_name: zabbix-agent
    ports:
      - 10050:10050
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
    restart: always
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"
    depends_on:
      - zabbix-server

  zabbix-agent2:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent2
    ports:
      - 10052:10050
    restart: always
    environment:
      - ZBX_HOSTNAME=MQTT
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_DEBUGLEVEL=5
    depends_on:
      - zabbix-server

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    volumes:
      - nodered-data:/data:rw
    ports:
      - 1880:1880
    depends_on:
      - zabbix-server

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - 9000:9000
      - 9443:9443

volumes:
 pgdata:
 nodered-data:
 pgadmin:
 portainer-data:
